[tool.poetry]
name = "ortho-remote-mac"
version = "0.1.0"
description = ""
authors = ["Akshay <araa@connect.ust.hk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.11.4"
mido = "^1.3.0"
python-rtmidi = "^1.5.5"
osascript = "^2020.12.3"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
